### ISSUE TITLE
Openwrt 21.02 compatibility

### ISSUE THREAD

**Issue by kerenskiy** [gSpotx2f/luci-app-temp-status#1]
Not work on openwrt 21.02, no Temperature info shown in Luci. 

Compiled from sources

**Comment by gSpotx2f** [comment]
@kerenskiy, show the output of this command: `ls /sys/class/thermal`.

**Comment by kerenskiy** [comment]
root@OpenWrt:~# ls /sys/class/thermal
cooling_device0  thermal_zone0

root@OpenWrt:~# ls /sys/class/hwmon/hwmon0
device       power        temp1_crit   uevent
name         subsystem    temp1_input

**Comment by gSpotx2f** [comment]
Ok, a few more commands:

	cat /sys/class/hwmon/hwmon0/temp1_input
	cat /sys/class/thermal/thermal_zone0/temp
	lua /usr/libexec/rpcd/luci.temp-status call getTempStatus

I added [support for hwmon](https://github.com/gSpotx2f/luci-app-temp-status/commit/f8dfa77caffa3ce30b9b2cde2c41834926f81ce2). Try the latest commit.

**Comment by gSpotx2f** [comment]
[Package for 19.07](https://github.com/gSpotx2f/luci-app-temp-status/tree/master/packages/19.07) is compatible with 21.02...

**Comment by kerenskiy** [comment]
Yes, all work fine!
