### ISSUE TITLE
doesn't work on openwrt 21.02.3 anymore on TP-LINK ARCHER A7 v5 EU/US

### ISSUE THREAD

**Issue by yesrab** [gSpotx2f/luci-app-temp-status#2]
doesn't work on openwrt 21.02.3 anymore on TP-LINK ARCHER A7 v5 after updating to openwrt 21.02.3

was perfectly working fine on openwrt 21.02.2 & 21.02.1.

System Log: https://pastebin.com/C107Y0iK

kernel log: https://www.toptal.com/developers/hastebin/fepesifivo.yaml

**Comment by gSpotx2f** [comment]
@yesrab, show the output of this commands: `ls /sys/class/thermal`, `ls /sys/class/hwmon`, `ls /sys/class/hwmon/hwmon0`, `lua /usr/libexec/rpcd/luci.temp-status call getTempStatus`.

**Comment by yesrab** [comment]
> @yesrab, show the output of this commands: `ls /sys/class/thermal`, `ls /sys/class/hwmon`, `ls /sys/class/hwmon/hwmon0`, `lua /usr/libexec/rpcd/luci.temp-status call getTempStatus`.

ls /sys/class/thermal : has no output 

ls /sys/class/hwmon : "ls: /sys/class/hwmon: No such file or directory"

ls /sys/class/hwmon/hwmon0 : "ls: /sys/class/hwmon/hwmon0: No such file or directory"

root@NODE1:~# lua /usr/libexec/rpcd/luci.temp-status call getTempStatus
[]root@NODE1:~#

**Comment by gSpotx2f** [comment]
No support for temperature sensors in sysfs. It looks like some driver or kernel module was not installed...
