### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by remittor** [gSpotx2f/luci-app-temp-status#5]
First variart: https://github.com/openwrt-xiaomi/luci-app-temp-status/commit/ac0150cbd0bd43172beab437f766fa1d641e9342
Second variant (best): https://github.com/openwrt-xiaomi/luci-app-temp-status/commit/456bbee1aeaa3bc423a9ef8db93ca501fcbb53a7

**Comment by gSpotx2f** [comment]
Hi! Unfortunately, I don't have a device with duplicate tsensors. If you don't mind, please test [this version](https://gist.github.com/gSpotx2f/2606aa65d2d90789417a2e7b0195000f) of /usr/libexec/rpcd/luci.temp-status.

    /usr/libexec/rpcd/luci.temp-status call getTempStatus
    ubus call luci.temp-status getTempStatus

**Comment by remittor** [comment]
Да. Ваш вариант тоже отлично работает.
Придётся мне заново в свой репо коммитить.

Так же посмотрите на коммит [Grouping all sensors with the name "sensor*_thermal" into one line](https://github.com/openwrt-xiaomi/luci-app-temp-status/commit/6228d752cbc836b8ecec4301fa673303cf13082d) : https://github.com/openwrt-xiaomi/luci-app-temp-status/commits/master/
Вот делает вот такое:
![image](https://github.com/gSpotx2f/luci-app-temp-status/assets/9350115/3f9ab6ad-f5d8-4d2e-8f04-86cad6ac721b)
(мин значение - медианное - макс значение)
А то надоело 10 сенсоров глазами смотреть.

**Comment by remittor** [comment]
Всё решил сделать немного иначе:
![image](https://github.com/gSpotx2f/luci-app-temp-status/assets/9350115/1e43cc82-b917-4d5c-a6e7-68c71d8cb813)

Вот сам код: https://github.com/openwrt-xiaomi/luci-app-temp-status/commit/a549cf4ca1d8d57526a673aa366103d18a7911bd
