### ISSUE TITLE
no build

### ISSUE THREAD

**Issue by ruslan66** [gSpotx2f/luci-app-temp-status#8]
I can't compile, I add (**https://github.com/gSpotx2f/luci-app-temp-status.git**) to feeds.conf, then (./scripts/feeds update -a) 

- in the console output 

(/home/ctos/openwrt/feeds/luciapptemp.tmp/info/.files-packageinfo.mk:1: *** target image does not contain “%”.  Stop.)

p.s.

ruantiblock_openwrt builds normally

**Comment by ruslan66** [comment]
I was able to create the ipk. It installs, but LuCI doesn't show anything. In terminal (lua /usr/libexec/rpcd/luci.temp-status call getTempStatus) it shows the temperature.

p.s. I am building based on the latest OWRT snapshot. 

If I put a ready ipk from your repository, everything is displayed correctly in LuCI. I compared the ready packages, the internals are almost identical. I don't know what to do.

**Comment by gSpotx2f** [comment]
There were changes in the last snapshots, the Makefile needs to be fixed. I'll do this when 24.x-rc1 is released.

**Comment by aliakin85** [comment]
can't install last snapshot Banana working with apk

**Comment by gSpotx2f** [comment]
>can't install last snapshot Banana working with apk

APK is not accepted yet in 24.10. Snapshot is a branch for developers, they usually know how to build packages from sources.
